var words = [{synonym : ["Abolished","ended"]},
{synonym : ["Abolishing","eliminating"]},
{synonym : ["Abound","numerous"]},
{synonym : ["Abrupt","sudden"]},
{synonym : ["abruptly","suddenly"]},
{synonym : ["Abundance","plenty"]},
{synonym : ["Abundant","plentiful"]},
{synonym : ["abundantly","plentifully"]},
{synonym : ["Accidental","unintentional"]},
{synonym : ["accompanied by","occurs together with"]},
{synonym : ["account for","explain"]},
{synonym : ["Accumulate","build up"]},
{synonym : ["Accumulating","increasing"]},
{synonym : ["accumulations","deposits"]},
{synonym : ["accustomed to","used to"]},
{synonym : ["Acquire","obtain"]}, 
{synonym : ["Adept","skillful"]},
{synonym : ["Adjacent","neighboring"]},
{synonym : ["Adjacent","nearby"]},
{synonym : ["admitted","accepted the truth of"]},
{synonym : ["Advantageous","beneficial"]},
{synonym : ["Afford","offer"]},
{synonym : ["agencies","forces"]},
{synonym : ["Aggregate","combined"]},
{synonym : ["Albeit","though"]},
{synonym : ["Allegedly","supposedly"]},
{synonym : ["alliances","partnerships"]},
{synonym : ["allowing for","making possible"]},
{synonym : ["Allusion","reference"]},
{synonym : ["Alteration","change"]},
{synonym : ["although","whereas"]},
{synonym : ["Amazing","Incredible","Fantastic","Fabulous","Astonishing","Extraordinary","unbelievable","improbable","wonderful"]},
{synonym : ["Ample","plentiful"]},
{synonym : ["analogous to","similar to"]},
{synonym : ["Anarchy","disorder"]},
{synonym : ["Ancestor","relative from earlier generation"]},
{synonym : ["Anger","enrage","infuriate","arouse","nettle","exasperate","inflame","madden"]},
{synonym : ["Angry","mad","furious","enraged","excited","wrathful","indignant","exasperated","aroused","inflamed"]},
{synonym : ["Answer","reply","Respond","retort","acknowledge"]},
{synonym : ["apart from","besides"]},
{synonym : ["apparent in","clearly seen in"]},
{synonym : ["appraisal","evaluation"]},
{synonym : ["Appreciated","understood"]},
{synonym : ["Approaches","nears"]},
{synonym : ["Approximating","resembling"]},
{synonym : ["Arduous","difficult"]},
{synonym : ["artificial","not real"]},
{synonym : ["ask","question","inquire of","seek information from","put a question to","demand request","expect","inquire","query","interrogate","examine","quiz"]},
{synonym : ["assistance","help"]},
{synonym : ["assisted in","helped with"]},
{synonym : ["assured","guaranteed"]},
{synonym : ["astonishing","incredible"]},
{synonym : ["Astoundingly","incredibly"]},
{synonym : ["at random","without a definite pattern"]},
{synonym : ["attain","achieve"]},
{synonym : ["Attains","reaches"]},
{synonym : ["attempt","seek"]},
{synonym : ["attest to","provide evidence of"]},
{synonym : ["Attributed","credited"]},
{synonym : ["attributes","ascribes","characteristics","properties"]},
{synonym : ["Authenticity","genuineness"]},
{synonym : ["Authoritative","official"]},
{synonym : ["autonomous","independent"]},
{synonym : ["Awful","dreadful","terrible","abominable","bad","poor","unpleasant"]},
{synonym : ["Bad","evil","immoral","wicked","corrupt","sinful","depraved","rotten","contaminated","spoiled","tainted","harmful","injurious","unfavorable","defective","inferior","imperfect","substandard","faulty","improper","inappropriate","unsuitable","disagreeable","unpleasant","cross","nasty","unfriendly","irascible","horrible","atrocious","outrageous","scandalous","infamous","wrong","noxious","sinister","putrid","snide","deplorable","dismal","gross","heinous","base","obnoxious","detestable","despicable","contemptible","foul","rank","ghastly","execrable"]},
{synonym : ["be deficient in","not have enough"]},
{synonym : ["Beautiful","pretty","lovely","handsome","attractive","gorgeous","dazzling","splendid","magnificent","comely","fair","ravishing","graceful","elegant","fine","exquisite","aesthetic","pleasing","shapely","delicate","stunning","glorious","heavenly","resplendent","radiant","glowing","blooming","sparkling"]},
{synonym : ["Begin","start","open","launch","initiate","commence","inaugurate","originate"]},
{synonym : ["Big","enormous","huge","immense","gigantic","vast","colossal","gargantuan","large","sizable","grand","great","tall","substantial","mammoth","astronomical","ample","broad","expansive","spacious","stout","tremendous","titanic","mountainous"]},
{synonym : ["Bombard","strike"]},
{synonym : ["Brainchild","invention"]},
{synonym : ["Brave","courageous","fearless","dauntless","intrepid","plucky","daring","heroic","valorous","audacious","bold","gallant valiant","doughty","mettlesome"]},
{synonym : ["Break","fracture","rupture","shatter","smash","wreck","crash","demolish","atomize"]},
{synonym : ["Bright","shining","shiny","gleaming brilliant","sparkling","shimmering radiant","vivid","colorful","lustrous","luminous","incandescent","intelligent","knowing","quick","witted","smart","intellectual"]},
{synonym : ["bulk","mass","largest part"]},
{synonym : ["bustling","busy","lively"]},
{synonym : ["Calm","quiet","peaceful","still","tranquil","mild","serene","smooth","composed","collected","unruffled","level","headed","unexcited","detached","aloof"]},
{synonym : ["capacity","available storage space"]},
{synonym : ["championed","supported"]},
{synonym : ["circumstances","conditions"]},
{synonym : ["Coating","layer"]},
{synonym : ["coincidence","at the same time and by chance"]},
{synonym : ["Come","approach","advance","near","arrive","reach"]},
{synonym : ["Commodity","product"]},
{synonym : ["compact","smaller"]},
{synonym : ["Compacted","compressed"]},
{synonym : ["Comparative","relative"]},
{synonym : ["Compelling","persuasive"]},
{synonym : ["compensating for","making up for"]},
{synonym : ["Complex","elaborates"]},
{synonym : ["complex","system"]},
{synonym : ["components","parts"]},
{synonym : ["composed of","made up of"]},
{synonym : ["comprehensive","complete"]},
{synonym : ["Compression","crushing"]},
{synonym : ["Comprise","make up"]},
{synonym : ["Comprising","made up of"]},
{synonym : ["Compulsorily","by requirement"]},
{synonym : ["Compulsory","required"]},
{synonym : ["concentrate","focus"]},
{synonym : ["conducive to","favorable to"]},
{synonym : ["Configuration","shape"]},
{synonym : ["Confined","limited Remnants","remains"]},
{synonym : ["Conjunction","combination"]},
{synonym : ["Consensus","agreement"]},
{synonym : ["consequent","resulting"]},
{synonym : ["Consequently","therefore","As a result"]},
{synonym : ["Considerable","significant"]},
{synonym : ["Considerably","significantly"]},
{synonym : ["Consistently","reliably"]},
{synonym : ["Conspicuous","noticeable","clearly visible"]},
{synonym : ["Constant","unchanging"]},
{synonym : ["consumed","eaten"]},
{synonym : ["consumption","utilization"]},
{synonym : ["Contention","debate"]},
{synonym : ["Context","environment"]},
{synonym : ["Continuous","uninterrupted"]},
{synonym : ["Contracted","shortened"]},
{synonym : ["Controversial","causing strong disagreement"]},
{synonym : ["Conventional","usual"]},
{synonym : ["Converge","move closer"]},
{synonym : ["Conversely","on the other hand"]},
{synonym : ["convinced","persuaded"]},
{synonym : ["Cool","chilly","cold","frosty","wintry","icy","frigid"]},
{synonym : ["Cope","adapt"]},
{synonym : ["coping with","managing"]},
{synonym : ["Core","center"]},
{synonym : ["countering","acting against"]},
{synonym : ["courses through","runs through"]},
{synonym : ["cramped","confined"]},
{synonym : ["Credible","believable"]},
{synonym : ["Crisis","critical situation"]},
{synonym : ["criteria","standards"]},
{synonym : ["Critical","crucial"]},
{synonym : ["critically","fundamentally"]},
{synonym : ["Crooked","bent","twisted","curved","hooked","zigzag"]},
{synonym : ["Crucial","important"]},
{synonym : ["Crude","rough"]},
{synonym : ["Cry","shout","yell","yowl scream","roar","bellow","weep","wail","sob","bawl"]},
{synonym : ["culminate","reach completion"]},
{synonym : ["culminated in","reached a high point with"]},
{synonym : ["Curious","strange"]},
{synonym : ["Current","present"]},
{synonym : ["Currently","at the present time"]},
{synonym : ["Cut","gash","slash","prick","nick","sever","slice","carve","cleave","slit","chop","crop","lop","reduce"]},
{synonym : ["Dangerous","perilous","hazardous","risky","uncertain","unsafe","Precarious"]},
{synonym : ["Dark","shadowy","unlit","murky","gloomy","dim","dusky","shaded","sunless","black","dismal","sad"]},
{synonym : ["deceiving","misleading"]},
{synonym : ["Decide","determine","settle","choose","resolve"]},
{synonym : ["decisive","determining"]},
{synonym : ["Declining","weakening"]},
{synonym : ["Definite","certain","sure","positive","determined","clear","distinct","obvious"]},
{synonym : ["Deliberations","discussions"]},
{synonym : ["Delicate","fragile"]},
{synonym : ["Delicious","savory","delectable","appetizing","luscious","scrumptious","palatable.","delightful","enjoyable","toothsome","exquisite","Tidbit"]},
{synonym : ["depicted","pictured"]},
{synonym : ["Depicts","portrays"]},
{synonym : ["derive","gain"]},
{synonym : ["Derive","obtain"]},
{synonym : ["Derives","obtains"]},
{synonym : ["Describe","portray","characterize","picture","narrate","relate","recount","represent","report","record"]},
{synonym : ["desolate","deserted"]},
{synonym : ["Despite","even though"]},
{synonym : ["Destroy","ruin","demolish","raze","waste","kill","slay","end","extinguish"]},
{synonym : ["Destroy","Demolish","Slay","Ruin","Raze"]},
{synonym : ["Detect","reveal","find"]},
{synonym : ["Detected","identified"]},
{synonym : ["detecting","discovering"]},
{synonym : ["Deteriorated","got worse"]},
{synonym : ["Detrimental","harmful"]},
{synonym : ["Devastated","destroyed"]},
{synonym : ["deviate","depart"]},
{synonym : ["Devised","created"]},
{synonym : ["devoid of","lacking in"]},
{synonym : ["devour","eat"]},
{synonym : ["Difference","disagreement","inequity","contrast","dissimilarity","incompatibility"]},
{synonym : ["Differing","varying"]},
{synonym : ["Diffusion","spread"]},
{synonym : ["Diligently","with persistence and hard work"]},
{synonym : ["Diminish","reduce"]},
{synonym : ["discern","identify"]},
{synonym : ["Dispersed","spread out"]},
{synonym : ["Disruption","disturbance"]},
{synonym : ["Distinctive","characteristic"]},
{synonym : ["Distributed","spread"]},
{synonym : ["Diverse","varied"]},
{synonym : ["Diversification","emergence of many varieties"]},
{synonym : ["diversified","varied"]},
{synonym : ["Diverted","shifted"]},
{synonym : ["Do","execute","enact","carry out","finish","conclude","effect","accomplish","achieve","attain"]},
{synonym : ["Document","record"]},
{synonym : ["Domain","field of expertise"]},
{synonym : ["dormant","inactive"]},
{synonym : ["dramatic","striking"]},
{synonym : ["Dramatically","greatly"]},
{synonym : ["drastically","severely"]},
{synonym : ["drastically","extensively"]},
{synonym : ["Drawback","problem"]},
{synonym : ["Dull","boring","tiring","tiresome","uninteresting","slow","dumb","stupid","unimaginative","lifeless","dead","insensible","tedious","wearisome","listless","expressionless","plain","monotonous","humdrum","dreary"]},
{synonym : ["Duplicated","copied"]},
{synonym : ["Durable","long lasting"]},
{synonym : ["duration","length"]},
{synonym : ["dwellers","inhabitants"]},
{synonym : ["Dwelling","living"]},
{synonym : ["Eager","keen","fervent","enthusiastic","involved","interested","alive to"]},
{synonym : ["efficacy","effectiveness"]},
{synonym : ["Efforts","attempts"]},
{synonym : ["elaborated upon","further developed"]},
{synonym : ["Elaborations","development"]},
{synonym : ["eliminate","get rid of"]},
{synonym : ["Embellishing","making more attractive"]},
{synonym : ["Emits","sends out"]},
{synonym : ["Empirical","based on observation"]},
{synonym : ["Encounters","meets"]},
{synonym : ["Encourages","promotes"]},
{synonym : ["End","stop","finish","terminate","conclude","close","halt","cessation","discontinuance"]},
{synonym : ["Endeavors","efforts"]},
{synonym : ["Endowing","providing"]},
{synonym : ["endured","survived"]},
{synonym : ["engraved","carved"]},
{synonym : ["Enhance","improve","increase"]},
{synonym : ["Enigmatic","mysterious"]},
{synonym : ["Enjoy","appreciate","delight in","be pleased","indulge in","luxuriate in","bask in","relish","devour","savor","like","experience"]},
{synonym : ["Enlist","recruit"]},
{synonym : ["enormous","colossal"]},
{synonym : ["Enormous","very large","extremely large"]},
{synonym : ["Ensuing","subsequent"]},
{synonym : ["Entirely","completely"]},
{synonym : ["entitled to","given the right to"]},
{synonym : ["Episodes","occurrence"]},
{synonym : ["erected","built"]},
{synonym : ["Eroded","worn down"]},
{synonym : ["Erratic","unpredictable"]},
{synonym : ["escalated","intensified"]},
{synonym : ["especially","notably"]},
{synonym : ["Ethic","set of moral principles"]},
{synonym : ["eventually","over time"]},
{synonym : ["Evolved","developed"]},
{synonym : ["Exceedingly","highly","extremely"]},
{synonym : ["Exceptional","extraordinary"]},
{synonym : ["Exceptionally","extraordinarily","unusually"]},
{synonym : ["Exclusive","sole"]},
{synonym : ["Exhaust","used up"]},
{synonym : ["Exhibit","show"]},
{synonym : ["Exhibited","displayed"]},
{synonym : ["expanded","was enlarged"]},
{synonym : ["Explain","elaborate","clarify","define","interpret","justify","account for"]},
{synonym : ["Exploit","make use of","use to advantage"]},
{synonym : ["Exploited","utilized"]},
{synonym : ["exposed","visible"]},
{synonym : ["extended","long"]},
{synonym : ["extensive","widespread","large"]},
{synonym : ["Extracted","removed"]},
{synonym : ["extracted from","taken out"]},
{synonym : ["facilitate","ease"]},
{synonym : ["Facilitates","makes easier"]},
{synonym : ["Fair","just","impartial","unbiased","objective","unprejudiced","honest"]},
{synonym : ["Faithful","accurate","exact"]},
{synonym : ["Fall","drop","descend","plunge","topple","tumble"]},
{synonym : ["FALSE","fake","fraudulent","counterfeit","spurious","untrue","unfounded","erroneous","deceptive","groundless"]},
{synonym : ["Famous","well known","renowned","celebrated","famed","eminent","illustrious","distinguished","noted","notorious"]},
{synonym : ["Fast","quick","rapid","speedy","fleet","hasty","snappy","mercurial","swiftly","rapidly","quickly","snappily","speedily","lickety split","posthaste","hastily","expeditiously","like a flash"]},
{synonym : ["Fat","stout","corpulent","fleshy","beefy","paunchy","plump","full","rotund","tubby","pudgy","chubby","chunky","burly","bulky","elephantine"]},
{synonym : ["Fear","fright","dread","terror","alarm","dismay","anxiety","scare","awe","horror","panic","apprehension"]},
{synonym : ["Feasible","achievable"]},
{synonym : ["feat","remarkable achievement"]},
{synonym : ["Flaw","fault"]},
{synonym : ["Flawed","incorrect"]},
{synonym : ["fleeing","running away from"]},
{synonym : ["flexible","adaptable"]},
{synonym : ["flourish","succeed"]},
{synonym : ["Flow","movement"]},
{synonym : ["Fluctuations","variations"]},
{synonym : ["Fly","soar","hover","flit","wing","flee","waft","glide","coast","skim","sail","cruise"]},
{synonym : ["following in time","subsequent"]},
{synonym : ["Foremost","earliest"]},
{synonym : ["fostered","encouraged"]},
{synonym : ["foul","pollute"]},
{synonym : ["fractures","cracks"]},
{synonym : ["Friction","conflict"]},
{synonym : ["Fringes","borders"]},
{synonym : ["Funny","humorous","amusing","droll","comic","comical","laughable","silly"]},
{synonym : ["Further","additional"]},
{synonym : ["Gains","increases"]},
{synonym : ["generated","produced"]},
{synonym : ["Generating","producing"]},
{synonym : ["Get","acquire","obtain","secure","procure","gain","fetch","find","score","accumulate","win","earn","rep","catch","net","bag","derive","collect","gather","glean","pick up","accept","come by","regain","salvage"]},
{synonym : ["Giant","huge"]},
{synonym : ["gifted","talented"]},
{synonym : ["give rise to","produce"]},
{synonym : ["Go","recede","depart","fade","disappear","move","travel","proceed."]},
{synonym : ["Good","excellent","fine","superior","wonderful","marvelous","qualified","suited","suitable","apt","proper","capable","generous","kindly","friendly","gracious","obliging","pleasant","agreeable","pleasurable","satisfactory","well behaved","obedient","honorable","reliable","trustworthy","safe","favorable","profitable","advantageous","righteous","expedient","helpful","valid","genuine","ample","salubrious","estimable","beneficial","splendid","great noble","worthy","first rate","top notch","grand","sterling","superb","respectable","edifying"]},
{synonym : ["gradually increase in number","accumulate"]},
{synonym : ["graphically","vividly"]},
{synonym : ["Great","noteworthy","worthy","distinguished","remarkable","grand","considerable","powerful","much","mighty"]},
{synonym : ["grew accustomed to","became used to"]},
{synonym : ["Gross","improper","rude","coarse","indecent","crude","vulgar","outrageous","extreme","grievous","shameful","uncouth","obscene","low"]},
{synonym : ["Guarantee","ensure"]},
{synonym : ["Halted","stopped"]},
{synonym : ["Happy","pleased","contented","satisfied","delighted","elated","joyful","cheerful","ecstatic","jubilant","gay","tickled","gratified","glad","blissful","overjoyed","Jaunty"]},
{synonym : ["harnessed","utilized"]},
{synonym : ["Hasten","accelerate"]},
{synonym : ["Hate","despise","loathe","detest","abhor","disfavor","dislike","disapprove","abominate"]},
{synonym : ["Have","hold","possess","own","contain","acquire","gain","maintain","believe","bear","beget","occupy","absorb","fill","enjoy"]},
{synonym : ["Help","aid","assist","support","encourage","back wait on","attend","serve","relieve","succor","benefit","befriend"]},
{synonym : ["Hence","therefore"]},
{synonym : ["heterogeneous","varied"]},
{synonym : ["Hide","conceal","cover","mask","cloak","camouflage","screen","shroud","veil"]},
{synonym : ["Highlights","emphasizes"]},
{synonym : ["Hints","clues"]},
{synonym : ["Humble","modest"]},
{synonym : ["Hurry","rush","run","speed","race","hasten","urge","accelerate","bustle"]},
{synonym : ["Hurt","damage","harm","injure","wound distress","afflict","pain"]},
{synonym : ["Idea","thought","concept","conception","notion","understanding","opinion","plan","view","belief"]},
{synonym : ["Illuminates","lights"]},
{synonym : ["Imaginative","creative"]},
{synonym : ["immobile","motionless"]},
{synonym : ["Impact","effect"]},
{synonym : ["Impediment","obstruction"]},
{synonym : ["impervious to","unaffected by"]},
{synonym : ["impetus","incentive"]},
{synonym : ["Impetus","stimulus"]},
{synonym : ["Implements","tools"]},
{synonym : ["Important","necessary","vital","critical","indispensable","valuable","essential","significant","primary","principal","considerable","famous","distinguished","notable","well known"]},
{synonym : ["impose on","place on"]},
{synonym : ["Impulse","basic motive"]},
{synonym : ["in the same breath","immediately"]},
{synonym : ["Inadvertently","unintentionally"]},
{synonym : ["incredible","unbelievable"]},
{synonym : ["indefinite period","whose end has not been determined"]},
{synonym : ["indigenous","native"]},
{synonym : ["indispensable","essential"]},
{synonym : ["Induce","stimulate"]},
{synonym : ["Inevitable","unavoidable"]},
{synonym : ["Inevitably","necessarily"]},
{synonym : ["Inflating","enlarging"]},
{synonym : ["infrequent","uncommon"]},
{synonym : ["ingenious","clever"]},
{synonym : ["Ingenuity","cleverness"]},
{synonym : ["Inhibits","restricts"]},
{synonym : ["inhospitable","not suitable"]},
{synonym : ["Initial","first"]},
{synonym : ["Initiated","started"]},
{synonym : ["Innumerable","countless"]},
{synonym : ["insight into","an understanding of"]},
{synonym : ["Installed","put in place"]},
{synonym : ["Instigated","caused"]},
{synonym : ["Instructive","informative"]},
{synonym : ["Intact","undamaged","whole"]},
{synonym : ["Integral","essential"]},
{synonym : ["intense","extreme","strong"]},
{synonym : ["Interesting","fascinating","engaging","sharp","keen bright","intelligent","animated","spirited","attractive","inviting","intriguing","provocative","though","provoking","challenging","inspiring","involving","moving","titillating","tantalizing","exciting","entertaining","piquant","lively","racy","spicy","engrossing","absorbing","consuming","gripping","arresting","enthralling","spellbinding","curious","captivating","enchanting","bewitching","appealing"]},
{synonym : ["interlocked","linked"]},
{synonym : ["Interplay","interaction"]},
{synonym : ["Interpreted","understood"]},
{synonym : ["Intricate","complex"]},
{synonym : ["Intrinsically","fundamentally"]},
{synonym : ["Invariably","always"]},
{synonym : ["Invoked","called upon","complicated"]},
{synonym : ["jointly","together"]},
{synonym : ["justified","supported"]},
{synonym : ["Keep","hold","retain","withhold","preserve","maintain","sustain","support"]},
{synonym : ["keep pace with","matched the increased in"]},
{synonym : ["Key","important","crucial","essential"]},
{synonym : ["Kill","slay","execute","assassinate","murder","destroy","cancel","abolish"]},
{synonym : ["Lavishly","richly"]},
{synonym : ["Lazy","indolent","slothful","idle","inactive","sluggish"]},
{synonym : ["legendary","famous"]},
{synonym : ["Legible","recognizable"]},
{synonym : ["legitimately","officially"]},
{synonym : ["lengthy","prolonged"]},
{synonym : ["Likewise","similarly"]},
{synonym : ["Little","tiny","small","diminutive","shrimp","runt","miniature","puny","exiguous","dinky","cramped","limited","itsy","bitsy","microscopic","slight","petite","minute"]},
{synonym : ["Location","place"]},
{synonym : ["Look","gaze","see","glance","watch","survey","study","seek","search for","peek","peep","glimpse","stare","contemplate","examine","gape","ogle","scrutinize","inspect","leer","behold","observe","view","witness","perceive","spy","sight","discover","notice","recognize","peer","eye","gawk","peruse","explore"]},
{synonym : ["Love","like","admire","esteem","fancy","care for","cherish","adore","treasure","worship","appreciate","savor"]},
{synonym : ["Luminous","bright"]},
{synonym : ["Make","create","originate","invent","beget","form","construct","design","fabricate","manufacture","produce","build","develop","do","effect","execute","compose","perform","accomplish","earn gain","obtain","acquire","get","Produce"]},
{synonym : ["Managed","were able"]},
{synonym : ["Mark","label","tag","price","ticket","impress","effect","trace","imprint","stamp","brand","sign","note","heed","notice","designate"]},
{synonym : ["marked","considerable"]},
{synonym : ["markedly","noticeably"]},
{synonym : ["Massive","enormous"]},
{synonym : ["Massive","very large"]},
{synonym : ["match","equal"]},
{synonym : ["Meager","very low","thin"]},
{synonym : ["mechanism for","means of"]},
{synonym : ["mechanisms of natural selection","ways natural selection works"]},
{synonym : ["Merge","combine"]},
{synonym : ["meticulously","carefully"]},
{synonym : ["Miniature","small"]},
{synonym : ["Minute","tiny"]},
{synonym : ["Mischievous","prankish","playful","naughty","roguish","waggish","impish","sportive"]},
{synonym : ["Modest","not large","small"]},
{synonym : ["Modified","changed"]},
{synonym : ["Modifies","changes"]},
{synonym : ["modify","change"]},
{synonym : ["Momentous","very important"]},
{synonym : ["Moody","temperamental","changeable","short tempered","glum","morose","sullen","mopish","irritable","testy","peevish","fretful","spiteful","sulky","touchy"]},
{synonym : ["Move","plod","go","creep","crawl","inch","poke","drag","toddle","shuffle","trot","dawdle","walk","traipse","mosey","jog","plug","trudge","slump","lumber","trail","lag","run","sprint","trip","bound","hotfoot","high tail","streak","stride","tear","breeze","whisk","rush","dash","dart","bolt","fling","scamper","scurry","skedaddle","scoot","scuttle","scramble","race","chase","hasten","hurry","hump","gallop","lope","accelerate","stir","budge","travel","wander","roam","journey","trek","ride","spin","slip","glide","slide","slither","coast","flow","sail","saunter","hobble","amble","Meander"]},
{synonym : ["Multitudinous","a great many"]},
{synonym : ["Mundane","ordinary"]},
{synonym : ["Neat","clean","orderly","tidy","trim","dapper","natty","smart","elegant","well organized","super","desirable","spruce","shipshape","well kept","shapely"]},
{synonym : ["neglected","failed"]},
{synonym : ["nevertheless","however"]},
{synonym : ["New","fresh","unique","original","unusual","novel","modern","current","recent"]},
{synonym : ["no wonder","unsurprising"]},
{synonym : ["Nonetheless","however"]},
{synonym : ["Norms","rules"]},
{synonym : ["noticeably","markedly"]},
{synonym : ["notions","idea"]},
{synonym : ["now and then","occasionally"]},
{synonym : ["objective","unbiased","purpose"]},
{synonym : ["obsession with","fixation on"]},
{synonym : ["Occasionally","once in a while"]},
{synonym : ["Old","feeble","frail","ancient","weak","aged","used","worn","dilapidated","ragged","faded","broken down","former","old fashioned","outmoded","passé","veteran","mature","venerable","primitive","traditional","archaic","conventional","customary","stale","musty","obsolete","extinct"]},
{synonym : ["Onset","start"]},
{synonym : ["Option","choice"]},
{synonym : ["order","sequence"]},
{synonym : ["out of sight","hidden"]},
{synonym : ["Outdated","old-fashioned"]},
{synonym : ["Overall","considered as a whole"]},
{synonym : ["overlie","cover"]},
{synonym : ["oversaw","supervised"]},
{synonym : ["overshadowed","distracted from"]},
{synonym : ["Overwhelming","powerful"]},
{synonym : ["Pales","loses significance"]},
{synonym : ["paradoxes","contradictions"]},
{synonym : ["Paradoxically","surprisingly"]},
{synonym : ["Part","potion","share","piece","allotment","section","fraction","fragment"]},
{synonym : ["Particular","specific"]},
{synonym : ["Peak","high point"]},
{synonym : ["penchant","inclination"]},
{synonym : ["Periodically","regularly"]},
{synonym : ["Perpetuated","continued"]},
{synonym : ["Perplexed","puzzled"]},
{synonym : ["persisted","continued"]},
{synonym : ["persistent","enduring"]},
{synonym : ["persistent","continue","long-lasting"]},
{synonym : ["perspective","viewpoint"]},
{synonym : ["Persuasively","convincingly"]},
{synonym : ["pertinent","relevant"]},
{synonym : ["pervasive","widespread"]},
{synonym : ["pessimistic","negative"]},
{synonym : ["Phenomena","occurrences"]},
{synonym : ["phenomenon","occurrence"]},
{synonym : ["pinpoint","locate exactly","identify precisely"]},
{synonym : ["Pioneers","leaders"]},
{synonym : ["Place","space","area","spot","plot","region","location","situation","position","residence","dwelling","set","site","station","status","state"]},
{synonym : ["Draw","Map","Diagram","Procedure","Method","Blueprint"]},
{synonym : ["Plan","plot","scheme","design","draw","map","diagram","procedure","arrangement","intention","device","contrivance","method","way","blueprint"]},
{synonym : ["plausible","believable","reasonable"]},
{synonym : ["Plausibly","Possibly"]},
{synonym : ["Plentiful","abundant"]},
{synonym : ["plugged","filled up"]},
{synonym : ["Popular","well liked","approved","accepted","favorite","celebrated","common","current"]},
{synonym : ["Portable","moveable"]},
{synonym : ["posed","presented"]},
{synonym : ["postulated","hypothesized"]},
{synonym : ["potent","powerful"]},
{synonym : ["potential","possible","capacity"]},
{synonym : ["Potentially","possibly"]},
{synonym : ["Practical","usable"]},
{synonym : ["precious","valuable"]},
{synonym : ["Precipitated","brought about"]},
{synonym : ["Precise","exact"]},
{synonym : ["Predicament","quandary","dilemma","pickle","problem plight","spot","scrape","jam"]},
{synonym : ["prediction","expectation"]},
{synonym : ["Predominant","most aggressive"]},
{synonym : ["Preposterous","unbelievable"]},
{synonym : ["prerequisite","requirement"]},
{synonym : ["preservative","something that keeps food fresh"]},
{synonym : ["Prestige","status"]},
{synonym : ["Presumably","supposedly","it can be assumed"]},
{synonym : ["prevalent","widespread"]},
{synonym : ["prime","high-quality"]},
{synonym : ["primordial","present at the very beginning of our solar system's formation"]},
{synonym : ["principal","major"]},
{synonym : ["prior to","before"]},
{synonym : ["Pristine","pure"]},
{synonym : ["Profound","far-reaching"]},
{synonym : ["Progressive","increase"]},
{synonym : ["Progressively","increasingly"]},
{synonym : ["prohibit","prevent"]},
{synonym : ["Projected","shown"]},
{synonym : ["Proliferation","growth","increase"]},
{synonym : ["Prolonged","extended"]},
{synonym : ["Promote","encourage"]},
{synonym : ["Promoted","encouraged","brought about"]},
{synonym : ["prone","likely"]},
{synonym : ["Pronounced","strongest"]},
{synonym : ["propagate","multiply"]},
{synonym : ["properly","appropriately"]},
{synonym : ["Propose","suggest"]},
{synonym : ["proposed","suggested"]},
{synonym : ["propulsion","moving forward"]},
{synonym : ["prospect","possibility"]},
{synonym : ["provoked","brought about"]},
{synonym : ["Put","place","set","attach","establish","assign","keep","save","set aside","effect","achieve","do","build"]},
{synonym : ["quantifiable","measurable"]},
{synonym : ["Quiet","silent","still","soundless","mute","tranquil","peaceful","calm","restful"]},
{synonym : ["radically","fundamentally"]},
{synonym : ["Ratio","proportion"]},
{synonym : ["Readily","easily"]},
{synonym : ["Reasonable","sufficient"]},
{synonym : ["rebound","recovery","recover"]},
{synonym : ["redundancy","duplication"]},
{synonym : ["Refined","improved"]},
{synonym : ["reflects","indicates"]},
{synonym : ["regarded","considered"]},
{synonym : ["Regrettably","unfortunately"]},
{synonym : ["regulating","controlling"]},
{synonym : ["Relatively","comparatively"]},
{synonym : ["Relics","remains"]},
{synonym : ["Reluctant","unwilling"]},
{synonym : ["remarkable change","dramatic increase"]},
{synonym : ["Remnants","remains"]},
{synonym : ["remoteness","isolation"]},
{synonym : ["renown","fame"]},
{synonym : ["renowned","famous"]},
{synonym : ["Repudiate","reject"]},
{synonym : ["Respectively","separately"]},
{synonym : ["Restricted","limited"]},
{synonym : ["resume","restart"]},
{synonym : ["Resurgence","comeback"]},
{synonym : ["retained","maintained"]},
{synonym : ["retarded","slowed down"]},
{synonym : ["reveal","show"]},
{synonym : ["revised","changed"]},
{synonym : ["Right","correct","accurate","factual","true","good","just","honest","upright","lawful","moral","proper","suitable","apt","legal","fair"]},
{synonym : ["ritual","ceremonial"]},
{synonym : ["Rival","competing"]},
{synonym : ["Roughly","approximately"]},
{synonym : ["Rudimentary","basic","primitive"]},
{synonym : ["Run","race","speed","hurry","hasten","sprint","dash","rush","escape","elope","flee"]},
{synonym : ["Sacred","holy"]},
{synonym : ["Say","tell","inform","notify","advise","relate","recount","narrate","explain","reveal","disclose","divulge","declare","command","order","bid","enlighten","instruct","insist","teach","train","direct","issue","remark","converse","speak affirm","suppose","utter","negate","express","verbalize","voice","articulate","pronounce","deliver","convey","impart","assert","state","allege","mutter","mumble","whisper","sigh","exclaim","yell","sing","yelp","snarl","hiss","grunt","snort","roar","bellow","thunder","boom scream","shriek","screech","squawk","whine","philosophize","stammer","stutter","lisp","drawl","jabber","protest","announce","swear","vow","content"]},
{synonym : ["scarcity","lack"]},
{synonym : ["Scared","afraid","frightened","alarmed","terrified","panicked","fearful","unnerved","insecure","timid","shy","skittish","jumpy","disquieted","worried","vexed","troubled","disturbed","horrified","terrorized","shocked","petrified","haunted","timorous","shrinking","tremulous","stupefied","paralyzed","stunned","apprehensive"]},
{synonym : ["Scenario","situation"]},
{synonym : ["Scores","large numbers"]},
{synonym : ["Sensible","reasonable"]},
{synonym : ["severe","extreme"]},
{synonym : ["Severed","cut of"]},
{synonym : ["severely","very seriously"]},
{synonym : ["shifts","changes"]},
{synonym : ["Show","display","exhibit","present","note","point to","indicate","explain","reveal","prove","demonstrate","expose"]},
{synonym : ["Signal","communicate"]},
{synonym : ["Signature","identifying mark"]},
{synonym : ["Significant","important","considerable"]},
{synonym : ["Simultaneously","at the same time"]},
{synonym : ["size up","evaluate"]},
{synonym : ["skeptical","doubtful"]},
{synonym : ["sloping","inclining"]},
{synonym : ["Slow","unhurried","gradual","leisurely","late","behind","tedious","slack"]},
{synonym : ["so much for","that is enough about"]},
{synonym : ["sovereign","master"]},
{synonym : ["Specific","particular"]},
{synonym : ["Spectacular","impressive"]},
{synonym : ["spheres","areas"]},
{synonym : ["splendid","magnificent"]},
{synonym : ["Sponsored","supported"]},
{synonym : ["static","unchanging"]},
{synonym : ["Status","importance"]},
{synonym : ["Stop","cease","halt","stay","pause","discontinue","conclude","end","finish","quit"]},
{synonym : ["Story","tale","myth","legend","fable","yarn","account","narrative","chronicle","epic","sage","anecdote","record","memoir"]},
{synonym : ["Strange","odd","peculiar","unusual","unfamiliar","uncommon","queer","weird","outlandish","curious","unique","exclusive","irregular"]},
{synonym : ["Strictly","exclusively"]},
{synonym : ["Striking","noticeable","attention getting"]},
{synonym : ["Stunning","impressive"]},
{synonym : ["subjected to","exposed to"]},
{synonym : ["Substantial","large"]},
{synonym : ["substantially","considerably"]},
{synonym : ["substantiated","confirmed"]},
{synonym : ["Suitable","appropriate"]},
{synonym : ["Superficially","without deeper analysis"]},
{synonym : ["Superseded","replaced"]},
{synonym : ["Suppress","stop by force"]},
{synonym : ["Surpass","be higher that","exceed"]},
{synonym : ["Surpassing","exceeding"]},
{synonym : ["surpluses","extra goods"]},
{synonym : ["Suspended","hung"]},
{synonym : ["sustain","maintain"]},
{synonym : ["sustained","uninterrupted"]},
{synonym : ["Take","hold","catch","seize","grasp","win","capture","acquire","pick","choose","select","prefer","remove","steal","lift","rob","engage","bewitch","purchase","buy","retract","recall","assume","occupy","consume"]},
{synonym : ["Tell","disclose","reveal","show","expose","uncover","relate","narrate","inform","advise","explain","divulge","declare","command","order","bid","recount","repeat"]},
{synonym : ["Termed","called","known as"]},
{synonym : ["terrestrial","land"]},
{synonym : ["the applications of ...","the uses to which ... was put"]},
{synonym : ["Therefore","as a result"]},
{synonym : ["Think","judge","assume","believe","consider","contemplate","reflect","mediate"]},
{synonym : ["thorough","comprehensive"]},
{synonym : ["Threatened","endangered"]},
{synonym : ["ties","connections"]},
{synonym : ["Timid","fearful"]},
{synonym : ["to have been accidental","to have occurred by chance"]},
{synonym : ["tolerant of","able to withstand"]},
{synonym : ["Traditionally","typically"]},
{synonym : ["transform","change"]},
{synonym : ["transformed","changed"]},
{synonym : ["transition","change"]},
{synonym : ["Trapped","caught"]},
{synonym : ["trappings","decorations"]},
{synonym : ["traumatic","highly stressful"]},
{synonym : ["Tremendous","huge"]},
{synonym : ["trend","tendency"]},
{synonym : ["Triggered","caused"]},
{synonym : ["Trivial","small"]},
{synonym : ["Trouble","distress","anguish","anxiety","worry","wretchedness","pain","danger","peril","disaster","grief","misfortune","difficulty","concern","pains","inconvenience","exertion","effort"]},
{synonym : ["TRUE","accurate","right","proper","precise","exact","valid","genuine","real","actual","trusty","steady","loyal"]},
{synonym : ["Turbulent","violent"]},
{synonym : ["Ugly","hideous","frightful","frightening","shocking","horrible","unpleasant","monstrous","terrifying","gross","grisly","ghastly","horrid","unsightly","plain","homely","evil","repulsive","repugnant","gruesome"]},
{synonym : ["ultimately","finally"]},
{synonym : ["unaltered","unchanged"]},
{synonym : ["Unanticipated","not expected"]},
{synonym : ["Undergoes","experiences"]},
{synonym : ["Undisputed","acknowledged"]},
{synonym : ["undoubtedly","certainly"]},
{synonym : ["Unearthed","discovered"]},
{synonym : ["Unhappy","miserable","uncomfortable","wretched","heart-broken","unfortunate","poor","downhearted","sorrowful","depressed","dejected","melancholy","glum","gloomy","dismal","discouraged","sad"]},
{synonym : ["uniformly","consistently"]},
{synonym : ["unique among","different from all other"]},
{synonym : ["Unprecedented","unlike anything in the past"]},
{synonym : ["Use","employ","utilize","exhaust","spend","consume","exercise"]},
{synonym : ["Vast","huge"]},
{synonym : ["Vastly","greatly"]},
{synonym : ["Verify","establish the truth of"]},
{synonym : ["Viable","able to survive"]},
{synonym : ["Vicinity","surrounding area"]},
{synonym : ["vigorously","strong and healthy"]},
{synonym : ["Virtually","almost","nearly","almost totally","nearly"]},
{synonym : ["Virtue","desirable quality"]},
{synonym : ["Vital","essential"]},
{synonym : ["vulnerable","open to attack"]},
{synonym : ["Whereas","while"]},
{synonym : ["widespread","common"]},
{synonym : ["Wrong","Incorrect","Inaccurate","Mistaken","Erroneous","Improper","Unsuitable"]}]